@startuml

skinparam DefaultFontName NanumBarunGothic
skinparam DefaultFontSize 13
skinparam monochrome true

:관리자: as Manager
:사용자: as User

User --> (로그인)
User --> (콘티 등록)
User --> (콘티 조회)
User --> (콘티 수정)
User --> (콘티 삭제)
User --> (쪽지 보내기)
Manager --> (사용자 관리)

Manager -|> User

note bottom of (콘티 조회)
	* 사용자(비로그인 포함)가 홈 페이지에
	    접속하면 홈 페이지에 최신/조회/인기
	    순으로 콘티들이 정렬되어 표시된다.
	* 홈 페이지에 나타난 콘티들은
	    자유롭게 조회할 수 있다.
	..조건..
	* 홈 페이지에는 콘티 제작자가 <공개>로
	    설정한 콘티만 표시될 수 있다.
	===
	* 사용자(비로그인 포함)는 하나의 콘티를
	    조회할 수 있다.
	* 한 콘티를 추천하거나 댓글을 달기 위해
	    사용자는 로그인해야 한다.
end note

note bottom of (콘티 등록)
	* 사용자가 홈 페이지에서 <콘티 만들기>를
	    선택하여 해당 페이지로 이동한다.
	* 사용자는 콘티 제작 페이지에서
	    콘티를 제작하고 공개 여부를 정하여
	    렌더링할 수 있다.
	* 사용자는 <내 콘티> 페이지에서 자신이
	    제작한/제작 중인 콘티를 조회하고
	    수정/삭제할 수 있다.
	..조건..
	* 로그인한 사용자만 이용 가능하다.
end note

note bottom of (사용자 관리)
	* 관리자는 사용자를 정지/삭제시킬 수 있다.
	    이 경우 해당 사용자의 DB 기록도 삭제된다.
	* 관리자는 콘티를 삭제할 수 있다.
end note

@enduml